### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by lahdekorpi**
Just added the license info and my name ;)

### CODE REVIEW

**Comment by xor-gate** [comment]
I had no clue from who this was, thanks for adding yourself and the license :+1:

**Comment by lahdekorpi** [comment]
Hopefully this repo will stop people from linking to my dev.hackers.fi directly, but instead pull the files for their own servers :joy:

**Comment by xor-gate** [comment]
It would be wise to link from your site to (a|your) github repo for this theme? Then we can remove the dev.hackers.fi folder in the lighttpd-dir-listing-themes repo?

**Comment by lahdekorpi** [comment]
The problem is the forum post in Lighttpd's website, there is a direct link to `http://dev.hackers.fi/lighttpd-dir.css` in there that people link directly to in their configs, what seems crazy to randomly include stuff from a random server...

**Comment by xor-gate** [comment]
Then your domain should just implement hotlinking prevention -_-'

**Comment by lahdekorpi** [comment]
I'm not worried about the bandwidth, it's just a couple of lines of code, I'm happy to donate if that helps anyone :smile: 
But I'm more worried about the security of those users / sysadmins that do stupid things, like linking to an external server...
I could replace that CSS with anything I want.

**Comment by xor-gate** [comment]
Yeah you are right on that one. That's life :_)

**Pull request merged**
